#1.0 : 플러그인이 처음 개발되었습니다.
#1.1 : 버그를 수정하였습니다.
#1.2 : 각종 오탈자를 수정하였습니다.
#1.3 : 카지노 운영관리 기능을 추가하였습니다.
#2.0 : GUI(베타)를 추가하였습니다.
#2.1 : 자동 공지 기능을 추가하였습니다.
#2.2 : 데이터 저장방식을 전부 수정하였습니다.
#2.3 : 야생 이동시 발생하는 게임모드 미변경 문제 수정하였습니다.
#2.4 : spigot-api-1.18.1 지원하도록 변경하였습니다.
#2.5 : 랜덤 텔레포트(베타) 추가하였습니다.
#3.0 : 셋홈기능이 추가되었습니다.
#3.1 : 티켓기능(베타)이 추가되었습니다.
#3.2 : 티켓 선물하기 기능이 추가되었습니다.
#3.3 : 콘피그 기능을 추가하였습니다.
#3.4 : 랜덤 텔레포트 기능 삭제 및 티켓 구매시 가격 예측을 추가하였습니다.
main: kr.twoyj.GUIPlugin
name: MyPlugin
version: 3.4
description: This Plugin is For Feather Server. ALL RIGHTS RESERVED.
auther: [yejunho10]
website: http://feather-s.kr/
api-version: 1.18
commands:
  mp:
    description: 해당 플러그인의 주된 명령어입니다.
  menu:
    description: GUI를 표시합니다.
  rules:
    description: 규칙을 출력합니다. (제작중)
  sethome:
    description: 집 정보를 지정합니다.
  home:
    description: 지정되어있는 집으로 텔레포트합니다.
  tk:
    description: 각종 거래에 사용될 수 있는 티켓에 관한 명려어입니다.
  mpr:
    description: 플러그인의 설정 파일을 불러옵니다.
  mps:
    description: 플러그인의 설정 파일을 저장합니다.
  mail:
    description: 심심해서 만든 명령어입니다.
permissions:
  myplugin.about:
    description: myplugin 정보 확인 권한입니다.
    default: true
  myplugin.teleport:
    description: myplugin(teleport) 전체 기능 이용 권한입니다.
    default: true
    children:
      myplugin.teleport.survival:
        description: myplugin의 survival로 teleport하는 기능 이용 권한입니다.
        default: true
      myplugin.teleport.casino:
        description: myplugin의 casino로 teleport하는 기능 이용 권한입니다.
        default: true
      myplugin.teleport.lobby:
        description: myplugin의 lobby로 teleport하는 기능 이용 권한입니다.
        default: true
      myplugin.teleport.spawn:
        description: myplugin의 spawn으로 teleport하는 기능 이용 권한입니다.
        default: true
      myplugin.teleport.minigame1:
        description: myplugin의 minigame1로 teleport하는 기능 이용 권한입니다
        default: true